#!/bin/bash
#args=("$@")
#nsp=${args[0]}

task_id=$SLURM_PROCID
node_id=$SLURM_NODEID
HOSTNAME=$(hostname)    # sometimes HOSTNAME seems to inherit from the submitting or launching node

# setup environment for python jobs
source ~/.bash_profile
module load lang/Python/2.7.10/python

await_pyomo_ns ()
{ 
    # wait for a pyro name server to be found successfully at the specified port
    # note: this is needed because dispatch_srvr (and maybe phsolverserver) retry
    # much less aggressively (if at all) when a port is specified. But we must use
    # a custom port to avoid conflicting with other jobs on the same cluster.
    until [[ $(pyro-nsc -p $nsp ping | grep 'NS is at') ]]
    do
        echo "task $task_id: Waiting for pyomo_ns to start at port $nsp..."
        sleep 2
    done
}

log_cpu ()
{ 
    # make a small delay so all the reports don't happen at the same time
    sleep $SLURM_NODEID
    minute_counter=0
    while ((1))
    do
        # keep showing cpu and memory usage until this task gets killed
        sleep 60
        ((minute_counter++))
        echo ""
        echo "Memory and CPU usage on $HOSTNAME after $minute_counter minutes:"
        free | head -n 2
        ps ux | sort -rk 3,3
        echo ""
    done
}

if [[ "$SLURM_GTIDS," = "$SLURM_PROCID,"* ]]
then
    # running the first task on the current node
    # start a memory and cpu logger
    log_cpu &
fi

# This runs only the runph command and name server on the first node,
# and runs one dispatch server and one solverserver in each task on the other nodes.
if [[ ",$SLURM_GTIDS," = *",0,"* ]]
then
    # this is the machine which should run task 0 (the runph command)
    if ((SLURM_PROCID == 0))
    then
        # this is task 0
        echo "Starting name server and runph in task $task_id on host $(hostname)"
        pyomo_ns -p $nsp -b $nsp -m &
        await_pyomo_ns
        # use eval instead of $cmd to expand arguments correctly, 
        # even if they are quoted strings with spaces
        eval $runph_cmd
    fi
else
    # worker node, not the first node
    echo "Starting dispatch_srvr and phsolverserver in task $task_id on host $(hostname)"
    await_pyomo_ns
    dispatch_srvr -p $nsp --allow-multiple-dispatchers &
    phsolverserver --traceback --pyro-port=$nsp
fi
